package handshake

import (
	"crypto/ed25519"
	"crypto/rand"
	"fmt"
	"sync"
	"time"
)

// SessionTTL is how long an approved session stays valid (Fase 1 §3 step 3:
// "un tiempo de vida corto (ej. 30 minutos)").
const SessionTTL = 30 * time.Minute

// Session is the ephemeral context a Fase 1 handshake produces. Fase 2
// names its JetStream subject after Session.ID; Fase 5 does the same for
// its events subject.
type Session struct {
	ID            string
	PeerMachineID string
	PeerPublicKey ed25519.PublicKey
	Params        Params
	// DestPath is the already-validated write target for Fase 2 (checked
	// against Params.AllowedDestPath by Responder.Handle before the
	// session was even created) — the receiver's stream consumer reads
	// this off the Session instead of trusting anything carried in the
	// JetStream chunk metadata itself.
	DestPath  string
	CreatedAt time.Time
	ExpiresAt time.Time
}

// newSessionID returns a random RFC 4122 v4 UUID string, generated by hand
// to avoid pulling in an external module for one function.
func newSessionID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("handshake: generate session id: %w", err)
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10

	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}

// SessionStore is the responder's in-memory registry of approved sessions
// (Fase 1 §3 step 3). Nothing here is persisted to disk — a restart means
// every in-flight session must re-handshake, which is intentional: session
// IDs are meant to be short-lived.
type SessionStore struct {
	mu       sync.Mutex
	sessions map[string]*Session
}

// NewSessionStore returns an empty store.
func NewSessionStore() *SessionStore {
	return &SessionStore{sessions: map[string]*Session{}}
}

// Create mints and registers a new Session for an approved handshake.
func (s *SessionStore) Create(peerMachineID string, peerPub ed25519.PublicKey, params Params, destPath string) (*Session, error) {
	id, err := newSessionID()
	if err != nil {
		return nil, err
	}

	now := time.Now()
	sess := &Session{
		ID:            id,
		PeerMachineID: peerMachineID,
		PeerPublicKey: peerPub,
		Params:        params,
		DestPath:      destPath,
		CreatedAt:     now,
		ExpiresAt:     now.Add(SessionTTL),
	}

	s.mu.Lock()
	s.sessions[id] = sess
	s.mu.Unlock()
	return sess, nil
}

// Get returns the session for id if it exists and has not expired. Fase 1
// §4: "cualquier mensaje... sin un Session ID previamente autorizado... es
// descartado sin procesar I/O" — callers must treat a false ok exactly like
// that, before touching any stream or disk I/O.
func (s *SessionStore) Get(id string) (*Session, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	sess, ok := s.sessions[id]
	if !ok {
		return nil, false
	}
	if time.Now().After(sess.ExpiresAt) {
		delete(s.sessions, id)
		return nil, false
	}
	return sess, true
}

// Close removes a session on normal completion (e.g. Is-Final-Chunk in Fase
// 2) or explicit abort.
func (s *SessionStore) Close(id string) {
	s.mu.Lock()
	delete(s.sessions, id)
	s.mu.Unlock()
}

// Sweep evicts all expired sessions and returns how many were removed —
// meant to be called periodically by the Daemon's watchdog (Fase 4).
func (s *SessionStore) Sweep() int {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now()
	n := 0
	for id, sess := range s.sessions {
		if now.After(sess.ExpiresAt) {
			delete(s.sessions, id)
			n++
		}
	}
	return n
}
